name = "OutlierDetectionNeighbors"
uuid = "51249a0a-cb36-4849-8e04-30c7f8d311bb"
authors = ["David Muhr <muhrdavid@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
